#ifndef HEROESENUM_H
#define HEROESENUM_H

#include <stdint.h>

enum RwRasterType
{
    rwRASTERTYPENORMAL = 0x0,
    rwRASTERTYPEZBUFFER = 0x1,
    rwRASTERTYPECAMERA = 0x2,
    rwRASTERTYPETEXTURE = 0x4,
    rwRASTERTYPECAMERATEXTURE = 0x5,
    rwRASTERTYPEMASK = 0x7,
    rwRASTERDONTALLOCATE = 0x80,
};

enum ENUM_TEAM_KIND
{
	TEAM_SONIC = 0x0,
	TEAM_DARK = 0x1,
	TEAM_ROSES = 0x2,
	TEAM_CHAOTIX = 0x3,
	TEAM_forEDIT = 0x4,
	NUM_TEAM_KINDS = 0x5,
};

enum ENUM_TEAMPLAY_MODE
{
    TEAM_MODE_IDLE = 0x0,
    TEAM_MODE_STAGE_START = 0x1,
    TEAM_MODE_STAGE_CLEAR = 0x2,
    TEAM_MODE_STAGE_GAMEOVER = 0x3,
    TEAM_MODE_FORMATION = 0x4,
    TEAM_MODE_FORMATION_START = 0x5,
    TEAM_MODE_FORMATION_LEADER_CHANGE = 0x6,
    TEAM_MODE_FORMATION_LEADER_CHANGE_R = 0x7,
    TEAM_MODE_FORMATION_RESET = 0x8,
    TEAM_MODE_SUPER_FORMATION_ATTACK = 0x9,
    TEAM_MODE_EVENT = 0xA,
    TEAM_MODE_SPEED_ROCKET_READY = 0xB,
    TEAM_MODE_SPEED_ROCKET_ACCEL1 = 0xC,
    TEAM_MODE_SPEED_ROCKET_ACCEL2 = 0xD,
    TEAM_MODE_FLY = 0xE,
    TEAM_MODE_BUSTER = 0xF,
    TEAM_MODE_TRIANGLE_DIVE = 0x10,
    TEAM_MODE_PLACEON = 0x11,
    TEAM_MODE_HANG = 0x12,
    TEAM_MODE_PINBALL = 0x13,
    TEAM_MODE_FORMATION_CHANGE_TO_SPEED = 0x14,
    TEAM_MODE_FORMATION_CHANGE_TO_FLY = 0x15,
    TEAM_MODE_FORMATION_CHANGE_TO_POWER = 0x16,
    TEAM_MODE_BOBSLEIGH = 0x17,
    NUM_TEAMPLAY_MODE = 0x18,
    TEAM_MODE_NO_RESERVATION = 0xFFFFFFFF,
};


enum ItemFlags : __int16
{
	Powerups_Barrier = 0x1,
	ItemFlags_Magnetic = 0x2,
	Powerups_SpeedShoes = 0x4,
	ItemFlags_ResetFlyTime = 0x8,
	Powerups1_10 = 0x10,
	Powerups1_20 = 0x20,
	Powerups1_40 = 0x40,
	Powerups1_80 = 0x80,
	ItemFlags_KnockbackLaunch = 0x400,
	ItemFlags_NotPosted = 0x800,
	ItemFlags_TeamBattleIsCPU = 0x1000,
	ItemFlags_2000 = 0x2000,
	ItemFlags_Dead = 0x4000,
	ItemFlags_Muteki = 0x8000,
};

enum ENUM_CHAR_MODE : __int16
{
	CharMode_UnderControl = 0x0,
	CharMode_Normal = 0x1,
	CharMode_FlyFormation = 0x2,
	CharMode_PowerAirSpin = 0x4,
	CharMode_PowerAttackHold = 0x8,
	CharMode_PowerAttackGather = 0x9,
	CharMode_ThunderShoot = 0xE,
	CharMode_Return = 0xF,
	CHAR_MODE_Inactive = 0x11,
	CHAR_MODE_Disabled = 0x12,
};

enum RwMatrixFlag
{
	rwMATRIXINTERNALIDENTITY = 0x20000,
};

enum Character : char
{
	Char_Sonic,
	Char_Knuckles,
	Char_Tails,
	Char_Shadow,
	Char_Omega,
	Char_Rouge,
	Char_Amy,
	Char_Big,
	Char_Cream,
	Char_Espio,
	Char_Vector,
	Char_Charmy
};

enum BTN_STATUS : uint8_t
{
	isOn = 0x1,
	isPress = 0x4,
	isRelease = 0x8,
};

enum PlayerMode
{
    ModeWait = 0x0,
    ModeRocketAccelCharge = 0x1,
    ModeJumping = 0x2,
    ModeFall = 0x4,
    ModeTripping = 0x5,
    ModeSpringLaunched = 0x6,
    ModePoleLaunched = 0x7,
    ModePushingSwitch = 0x9,
    ModeHurt = 0xA,
    ModeCrash = 0xB,
    ModeRunning = 0xE,
    ModeJumpDash = 0xF,
    ModeRidingPinballRail = 0x12,
    ModeMovingTowardsPowerCharacter = 0x13,
    ModeSpinningOnPowerCharacter = 0x14,
    ModeAI_TooFar = 0x1A,
    ModeAIMaybe_Returning = 0x1B,
    ModeCanonFired = 0x1C,
    ModeGrinding = 0x1D,
    ModeRainbowRingTrick = 0x1E,
    ModeGrabbing = 0x1F,
    ModeObjectControl_Spinning = 0x21,
    ModeStandingWithSwitch = 0x22,
    ModeGrabbingOntoSwitch = 0x23,
    ModeSwitchRelease_Maybe = 0x24,
    ModePullingSwitch = 0x25,
    ModeCaptured = 0x26,
    ModeVanished = 0x27,
    ModePinballMode = 0x28,
    ModeSpeedFly_Gliding = 0x29,
    ModeEvent = 0x2B,
    ModeDead = 0x2C,
    ModeFly = 0x34,
    ModeRocketAccelRelease = 0x36,
    ModePower_Attack1 = 0x38,
    ModePower_Attack2 = 0x39,
    ModeThunderShootSpinning = 0x3B,
    ModeLightDash = 0x3D,
    ModeAirPowerAttackSpinMode = 0x3E,
    ModeAirPowerAttackInPosition = 0x3F,
    ModePinballRelated_apparently = 0x3F,
    ModeAirPowerAttackShot = 0x40,
    ModeTornado = 0x42,
    ModePower_Gliding = 0x43,
    ModeWallStand = 0x44,
    ModeWallJump = 0x45,
    ModeAmy_Tornado = 0x48,
    ModeTails_RingThrow = 0x4B,
    ModeHammerFloat = 0x4D,
    ModeLightSpeedDash = 0x53,
    ModeKick = 0x54,
    ModeSFA = 0x55,
};

enum PlayerAnim
{
    Animation_Stand = 0x0,
    Animation_Idle = 0x2,
    Animation_Idle2 = 0x3,
    Motion_Walk = 0x4,
    Motion_Jog = 0x5,
    Motion_Run = 0x6,
    Motion_Rush = 0x7,
    Motion_Dash = 0x8,
    Animation_Roll = 0x9,
    Animation_RollStill_ = 0xA,
    Animation_Launched = 0xB,
    Animation_Falling = 0xC,
    Animation_FallingFast = 0xD,
    Animation_StandingLand = 0xE,
    Animation_StandingLand2 = 0xF,
    Animation_LandWalking = 0x10,
    Animation_SkidStart = 0x11,
    Animation_Skid = 0x12,
    Animation_SkidStop = 0x13,
    Animation_SkidTurnLeftStart = 0x14,
    Animation_SkidTurnLeftStop = 0x15,
    Animation_HurtStart = 0x16,
    Animation_HurtAir = 0x17,
    Animation_HurtGround = 0x18,
    Animation_FanFloat = 0x19,
    Animation_Land_ = 0x1A,
    Animation_TurnAroundLeft = 0x1B,
    Animation_TurnAroundRight = 0x1C,
    Animation_StopNoTurnAround_ = 0x1D,
    Animation_TeamBlast = 0x1F,
    Animation_TeamBlastEnd = 0x20,
    Animation_Push = 0x21,
    Animation_Pull = 0x22,
    Animation_Grab = 0x23,
    Animation_Holding = 0x24,
    Animation_LetGo = 0x25,
    Animation_PushLarge = 0x26,
    Animation_PullLarge = 0x27,
    Animation_GrabLarge = 0x28,
    Animation_HoldingLarge = 0x29,
    Animation_LetGoLarge = 0x2A,
    Animation_2PIntro = 0x2B,
    Animation_2PIntroEnd = 0x2C,
    Animation_2PIntroInactive_ = 0x2D,
    Animation_VictoryPose = 0x2E,
    Animation_VictoryPoseEnd = 0x2F,
    Animation_Captured_ = 0x30,
    Animation_Dead = 0x31,
    Animation_StunnedOrDead2 = 0x32,
    Animation_TripStart = 0x33,
    Animation_Trip = 0x34,
    Animation_TripEnd = 0x35,
    Animation_JumpCurl = 0x36,
    Animation_JumpRoll = 0x37,
    Animation_JumpUncurl = 0x38,
    Animation_JumpFall = 0x39,
    Animation_JumpPad = 0x3B,
    Animation_FlightFormationRelated_ = 0x3C,
    Animation_Hang = 0x3D,
    Animation_Trick = 0x3E,
    Animation_Glide = 0x3F,
    Animation_FlightFormationStill = 0x40,
    Animation_FlightFormationMove = 0x41,
    Animation_FlightFormationRelated = 0x42,
    Animation_FlightFormationRelated2 = 0x43,
    Animation_RollRelated = 0x44,
    Animation_JumpDash = 0x45,
    Animation_OnRail = 0x46,
    Animation_GrindHold = 0x49,
    Animation_GrindStart = 0x4C,
    Animation_GrindEnd = 0x4D,
    Animation_BottomFlyFormationRail = 0x4E,
    Animation_SuperTeamBlastIntro = 0x52,
    Animation_SuperTeamBlast = 0x53,
    Animation_SuperVictoryPose = 0x54,
    Animation_SuperVictoryPoseEnd = 0x55,
    Animation_RingThrow = 0x5A,
    Animation_LightDash = 0x5A,
    Animation_PowerAirAttack = 0x5A,
    Animation_WallStand = 0x5B,
    Animation_PowerAttack = 0x5B,
    Animation_FlyBobsled = 0x5C,
    Animation_WallJump = 0x5C,
    Animation_PowerAttack2 = 0x5C,
    Animation_BackFlip = 0x5D,
    Animation_PowerAttack3Start = 0x5D,
    Animation_SideFlip = 0x5E,
    Animation_PowerAttack3 = 0x5E,
    Animation_BackFlip2 = 0x5F,
    Animation_PowerAttack3End = 0x5F,
    Animation_LeafTornado = 0x60,
    Animation_PowerPunch2 = 0x60,
    Animation_HammerSwingStart = 0x61,
    Animation_PowerPunch3 = 0x61,
    Animation_HammerSwing = 0x62,
    Animation_PowerExtraAttack = 0x62,
    Animation_HammerSwingEnd = 0x63,
    Animation_HammerTornado = 0x64,
    Animation_HammerTornadoEnd = 0x65,
    Animation_HammerFloat = 0x66,
    Animation_PowerBobsled = 0x66,
    Animation_ThrowStar = 0x67,
    Animation_SlideKick = 0x68,
};

enum Enum_EffWinkMode : int
{
};

enum RwStreamType {
    rwNASTREAM = 0,
    rwSTREAMFILE = 1,
    rwSTREAMFILENAME = 2,
    rwSTREAMMEMORY = 3,
    rwSTREAMCUSTOM = 4,
    rwSTREAMTYPEFORCEENUMSIZEINT = 2147483647,
};

enum RwStreamAccessType {
    rwNASTREAMACCESS = 0,
    rwSTREAMREAD = 1,
    rwSTREAMWRITE = 2,
    rwSTREAMAPPEND = 3,
    rwSTREAMACCESSTYPEFORCEENUMSIZEINT = 2147483647,
};

enum RwEngineStatus
{
    rwENGINESTATUSIDLE = 0x0,
    rwENGINESTATUSINITED = 0x1,
    rwENGINESTATUSOPENED = 0x2,
    rwENGINESTATUSSTARTED = 0x3,
};

enum ENUM_FORMATION
{
    FORMATION_SPEED = 0x0,
    FORMATION_POWER = 0x1,
    FORMATION_FLY = 0x2,
    FORMATION_FLY_FLYING = 0x3,
    FORMATION_ROCKET_ACCEL = 0x4,
    FORMATION_TRIANGLE_DIVE = 0x5,
    FORMATION_LINE_DIVE = 0x6,
    FORMATION_SPEED_HANG = 0x7,
    FORMATION_POWER_HANG = 0x8,
    FORMATION_FLY_HANG = 0x9,
    FORMATION_SPEED_PINBALL = 0xA,
    FORMATION_POWER_PINBALL = 0xB,
    FORMATION_FLY_PINBALL = 0xC,
    NUM_FORMATIONS = 0xD,
};

enum ENUM_PLAYER_VOICE
{
    ENUM_PLAYER_VOICE_SE_START = 0xFFFFFFFF,
    ENUM_PLAYER_VOICE_SE_ERROR = 0xFFFFFFFF,
    ENUM_PLAYER_VOICE_JUMP = 0x0,
    ENUM_PLAYER_VOICE_ACTION0 = 0x1,
    ENUM_PLAYER_VOICE_KICK = 0x1,
    ENUM_PLAYER_VOICE_HAMMER = 0x1,
    ENUM_PLAYER_VOICE_SHURIKEN = 0x1,
    ENUM_PLAYER_VOICE_DRBOMB = 0x1,
    ENUM_PLAYER_VOICE_CHEEZE = 0x1,
    ENUM_PLAYER_VOICE_STING = 0x1,
    ENUM_PLAYER_VOICE_ATTACK1 = 0x1,
    ENUM_PLAYER_VOICE_ACTION1 = 0x2,
    ENUM_PLAYER_VOICE_ROCKETACCEL = 0x2,
    ENUM_PLAYER_VOICE_THUNDERSHOOT = 0x2,
    ENUM_PLAYER_VOICE_ATTACK2 = 0x2,
    ENUM_PLAYER_VOICE_BIGFISH = 0x2,
    ENUM_PLAYER_VOICE_VECTORBREATH = 0x2,
    ENUM_PLAYER_VOICE_ACTION2 = 0x3,
    ENUM_PLAYER_VOICE_TORNADO = 0x3,
    ENUM_PLAYER_VOICE_FLYDASH = 0x3,
    ENUM_PLAYER_VOICE_VDUNK = 0x3,
    ENUM_PLAYER_VOICE_BIGPRESS = 0x3,
    ENUM_PLAYER_VOICE_VECTORHAMMER = 0x3,
    ENUM_PLAYER_VOICE_HANG = 0x4,
    ENUM_PLAYER_VOICE_CHANGE_FORMATION = 0x5,
    ENUM_PLAYER_VOICE_DAMAGE = 0x6,
    ENUM_PLAYER_VOICE_PUSH_PULL = 0x7,
    ENUM_PLAYER_VOICE_OTTO = 0x8,
    ENUM_PLAYER_VOICE_ACTION3 = 0x9,
    ENUM_PLAYER_VOICE_RAREADY = 0x9,
    ENUM_PLAYER_VOICE_FLY = 0x9,
    ENUM_PLAYER_VOICE_FDUNK = 0x9,
    ENUM_PLAYER_VOICE_BIGUMBRELLA = 0x9,
    ENUM_PLAYER_VOICE_VECTORBUBBLEGUM = 0x9,
    NUM_ENUM_PLAYER_VOICE_SE = 0xA,
    ENUM_PLAYER_VOICE_ADX_START = 0xA,
    ENUM_PLAYER_VOICE_2PINTRO_ACTION = 0xA,
    ENUM_PLAYER_VOICE_2PINTRO_BATTLE = 0xB,
    ENUM_PLAYER_VOICE_2PINTRO_RING = 0xC,
    ENUM_PLAYER_VOICE_2PINTRO_QUICK = 0xD,
    ENUM_PLAYER_VOICE_2PINTRO_EXPERT = 0xE,
    ENUM_PLAYER_VOICE_2PVICTORY_ACTION = 0xF,
    ENUM_PLAYER_VOICE_2PVICTORY_BATTLE = 0x10,
    ENUM_PLAYER_VOICE_2PVICTORY_SPECIAL = 0x11,
    ENUM_PLAYER_VOICE_2PVICTORY_RING = 0x12,
    ENUM_PLAYER_VOICE_2PVICTORY_BOB = 0x13,
    ENUM_PLAYER_VOICE_2PVICTORY_QUICK = 0x14,
    ENUM_PLAYER_VOICE_2PVICTORY_EXPERT = 0x15,
    ENUM_PLAYER_VOICE_2PBATTLE_DROP_1 = 0x16,
    ENUM_PLAYER_VOICE_2PBATTLE_DROP_2 = 0x17,
    ENUM_PLAYER_VOICE_2PBOB_OVERTAKE = 0x18,
    ENUM_PLAYER_VOICE_2PBOB_OVERTAKEN = 0x19,
    ENUM_PLAYER_VOICE_KILLED = 0x1A,
    ENUM_PLAYER_VOICE_PARALYZED = 0x1B,
    ENUM_PLAYER_VOICE_FALL_OUT = 0x1C,
    ENUM_PLAYER_VOICE_CAPTURED = 0x1D,
    ENUM_PLAYER_VOICE_COME_AGAIN = 0x1E,
    ENUM_PLAYER_VOICE_PRESSED = 0x1F,
    ENUM_PLAYER_VOICE_CAPTURED_1 = 0x20,
    ENUM_PLAYER_VOICE_CAPTURED_2 = 0x21,
    ENUM_PLAYER_VOICE_ATO100MAI = 0x22,
    ENUM_PLAYER_VOICE_JIKANGIREMADIKA = 0x22,
    ENUM_PLAYER_VOICE_ATO50TAI = 0x22,
    ENUM_PLAYER_VOICE_ATO30TAI = 0x22,
    ENUM_PLAYER_VOICE_ATO50MAI = 0x22,
    ENUM_PLAYER_VOICE_ATO10MAI = 0x22,
    ENUM_PLAYER_VOICE_TB_READY = 0x23,
    ENUM_PLAYER_VOICE_TB_CALL = 0x24,
    ENUM_PLAYER_VOICE_TB_REPLY = 0x25,
    ENUM_PLAYER_VOICE_TB_BLAST = 0x26,
    ENUM_PLAYER_VOICE_TRICK_1 = 0x27,
    ENUM_PLAYER_VOICE_TRICK_2 = 0x28,
    ENUM_PLAYER_VOICE_TRICK_3 = 0x29,
    ENUM_PLAYER_VOICE_TRICK_4 = 0x2A,
    ENUM_PLAYER_VOICE_TRICK_5 = 0x2B,
    ENUM_PLAYER_VOICE_ITEM_GET_1 = 0x2C,
    ENUM_PLAYER_VOICE_ITEM_GET_2 = 0x2D,
    ENUM_PLAYER_VOICE_LEVEL_UP = 0x2E,
    ENUM_PLAYER_VOICE_CLEAR = 0x2F,
    ENUM_PLAYER_VOICE_RANK_A = 0x30,
    ENUM_PLAYER_VOICE_RANK_B = 0x31,
    ENUM_PLAYER_VOICE_RANK_C = 0x32,
    ENUM_PLAYER_VOICE_RANK_D = 0x33,
    ENUM_PLAYER_VOICE_RANK_E = 0x34,
    ENUM_PLAYER_VOICE_CLEAR_EGGHAWK = 0x35,
    ENUM_PLAYER_VOICE_CLEAR_TEAM_1 = 0x36,
    ENUM_PLAYER_VOICE_CLEAR_ZAKO_1 = 0x37,
    ENUM_PLAYER_VOICE_CLEAR_EGGALBATROSS = 0x38,
    ENUM_PLAYER_VOICE_CLEAR_TEAM_2 = 0x39,
    ENUM_PLAYER_VOICE_CLEAR_ZAKO_2 = 0x3A,
    ENUM_PLAYER_VOICE_CLEAR_KINGPAWN = 0x3B,
    ENUM_PLAYER_VOICE_WAIT_1 = 0x3C,
    ENUM_PLAYER_VOICE_WAIT_2 = 0x3D,
    ENUM_PLAYER_VOICE_WAIT_3 = 0x3E,
    ENUM_PLAYER_VOICE_WAIT_STAGE_01 = 0x3F,
    ENUM_PLAYER_VOICE_WAIT_STAGE_02 = 0x40,
    ENUM_PLAYER_VOICE_WAIT_STAGE_03 = 0x41,
    ENUM_PLAYER_VOICE_WAIT_STAGE_04 = 0x42,
    ENUM_PLAYER_VOICE_WAIT_STAGE_05 = 0x43,
    ENUM_PLAYER_VOICE_WAIT_STAGE_06 = 0x44,
    ENUM_PLAYER_VOICE_WAIT_STAGE_07 = 0x45,
    ENUM_PLAYER_VOICE_WAIT_STAGE_08 = 0x46,
    ENUM_PLAYER_VOICE_WAIT_STAGE_09 = 0x47,
    ENUM_PLAYER_VOICE_WAIT_STAGE_10 = 0x48,
    ENUM_PLAYER_VOICE_WAIT_STAGE_11 = 0x49,
    ENUM_PLAYER_VOICE_WAIT_STAGE_12 = 0x4A,
    ENUM_PLAYER_VOICE_WAIT_STAGE_13 = 0x4B,
    ENUM_PLAYER_VOICE_WAIT_STAGE_14 = 0x4C,
    ENUM_PLAYER_VOICE_EGGHAWK_START = 0x4D,
    ENUM_PLAYER_VOICE_EGGHAWK_MORTAL = 0x4E,
    ENUM_PLAYER_VOICE_TEAM_1_START = 0x4F,
    ENUM_PLAYER_VOICE_TEAM_1_DROP_OUT_1 = 0x50,
    ENUM_PLAYER_VOICE_TEAM_1_DROP_OUT_2 = 0x51,
    ENUM_PLAYER_VOICE_ZAKO_1_START = 0x52,
    ENUM_PLAYER_VOICE_ZAKO_1_DEFEAT_X = 0x53,
    ENUM_PLAYER_VOICE_ZAKO_1_DEFEAT_Y = 0x54,
    ENUM_PLAYER_VOICE_EGGALBATROSS_START = 0x55,
    ENUM_PLAYER_VOICE_EGGALBATROSS_DESTROY_C = 0x56,
    ENUM_PLAYER_VOICE_EGGALBATROSS_DESTROY_B = 0x57,
    ENUM_PLAYER_VOICE_TEAM_2_START = 0x58,
    ENUM_PLAYER_VOICE_TEAM_2_DROP_OUT_1 = 0x59,
    ENUM_PLAYER_VOICE_TEAM_2_DROP_OUT_2 = 0x5A,
    ENUM_PLAYER_VOICE_ZAKO_2_START = 0x5B,
    ENUM_PLAYER_VOICE_ZAKO_2_DEFEAT_X = 0x5C,
    ENUM_PLAYER_VOICE_ZAKO_2_DEFEAT_Y = 0x5D,
    ENUM_PLAYER_VOICE_KINGPAWN_START = 0x5E,
    ENUM_PLAYER_VOICE_KINGPAWN_HP_2_THIRD = 0x5F,
    ENUM_PLAYER_VOICE_KINGPAWN_HP_1_THIRD = 0x60,
    ENUM_PLAYER_VOICE_METALSONIC_START = 0x61,
    ENUM_PLAYER_VOICE_METALSONIC_END = 0x62,
    NUM_ENUM_PLAYER_VOICE_ADX = 0x63,
    NUM_ENUM_PLAYER_VOICE = 0x63,
};

enum OBJ_MOG_BOUND_MODE {
    OBJ_MOG_BOUND_MODE_POINT = 0,
    OBJ_MOG_BOUND_MODE_EASY = 1,
    OBJ_MOG_BOUND_MODE_REAL = 2,
    NUM_OBJ_MOG_BOUND_MODE = 3,
};


enum RwOpCombineType : __int32
{
    rwCOMBINEREPLACE = 0x0,
    rwCOMBINEPRECONCAT = 0x1,
    rwCOMBINEPOSTCONCAT = 0x2,
};

#endif