namespace Heroes.SDK.Definitions.Enums.Custom
{
    public enum Players : int
    {
        One,
        Two,
        Three,
        Four
    }

   public enum PlayerMode
    {
       Wait = 0x0,
       RocketAccelCharge = 0x1,
       Jumping = 0x2,
       Fall = 0x4,
       Tripping = 0x5,
       SpringLaunched = 0x6,
       PoleLaunched = 0x7,
       PushingSwitch = 0x9,
       Hurt = 0xA,
       Crash = 0xB,
       Running = 0xE,
       JumpDash = 0xF,
       RidingPinballRail = 0x12,
       MovingTowardsPowerCharacter = 0x13,
       SpinningOnPowerCharacter = 0x14,
       AI_TooFar = 0x1A,
       AIMaybe_Returning = 0x1B,
       CanonFired = 0x1C,
       Grinding = 0x1D,
       RainbowRingTrick = 0x1E,
       Grabbing = 0x1F,
       ObjectControl_Spinning = 0x21,
       StandingWithSwitch = 0x22,
       GrabbingOntoSwitch = 0x23,
       SwitchRelease_Maybe = 0x24,
       PullingSwitch = 0x25,
       Captured = 0x26,
       Vanished = 0x27,
       PinballMode = 0x28,
       SpeedFly_Gliding = 0x29,
       Event = 0x2B,
       Dead = 0x2C,
       Fly = 52,
       FlyTired = 53,
       RocketAccelRelease = 0x36,
       Power_Attack1 = 0x38,
       Power_Attack2 = 0x39,
       ThunderShootSpinning = 0x3B,
       LightDash = 0x3D,
       AirPowerAttackSpinMode = 0x3E,
       AirPowerAttackInPosition = 0x3F,
       PinballRelated_apparently = 0x3F,
       AirPowerAttackShot = 0x40,
       Tornado = 0x42,
       Power_Gliding = 0x43,
       WallStand = 0x44,
       WallJump = 0x45,
       Amy_Tornado = 0x48,
       Cream_CheeseAtk = 73,
       Tails_RingThrow = 0x4B,
       HammerFloat = 77,
       LightSpeedDash = 0x53,
       Kick = 0x54,
       SFA = 0x55,
    };

    public enum PlayerAnim
    {
        Animation_Stand = 0,
        Animation_Idle = 2,
        Animation_Idle2 = 3,
        Motion_Walk = 4,
        Motion_Jog = 5,
        Motion_Run = 6,
        Motion_Rush = 7,
        Motion_Dash = 8,
        Animation_Roll = 9,
        Animation_RollStill_ = 10,
        Animation_Launched = 11,
        Animation_Falling = 12,
        Animation_FallingFast = 13,
        Animation_StandingLand = 14,
        Animation_StandingLand2 = 15,
        Animation_LandWalking = 16,
        Animation_SkidStart = 17,
        Animation_Skid = 18,
        Animation_SkidStop = 19,
        Animation_SkidTurnLeftStart = 20,
        Animation_SkidTurnLeftStop = 21,
        Animation_HurtStart = 22,
        Animation_HurtAir = 23,
        Animation_HurtGround = 24,
        Animation_FanFloat = 25,
        Animation_Land_ = 26,
        Animation_TurnAroundLeft = 27,
        Animation_TurnAroundRight = 28,
        Animation_StopNoTurnAround_ = 29,
        Animation_TeamBlast = 31,
        Animation_TeamBlastEnd = 32,
        Animation_Push = 33,
        Animation_Pull = 34,
        Animation_Grab = 35,
        Animation_Holding = 36,
        Animation_LetGo = 37,
        Animation_PushLarge = 38,
        Animation_PullLarge = 39,
        Animation_GrabLarge = 40,
        Animation_HoldingLarge = 41,
        Animation_LetGoLarge = 42,
        Animation_2PIntro = 43,
        Animation_2PIntroEnd = 44,
        Animation_2PIntroInactive_ = 45,
        Animation_VictoryPose = 46,
        Animation_VictoryPoseEnd = 47,
        Animation_Captured_ = 48,
        Animation_Dead = 49,
        Animation_StunnedOrDead2 = 50,
        Animation_TripStart = 51,
        Animation_Trip = 52,
        Animation_TripEnd = 53,
        Animation_JumpCurl = 54,
        Animation_JumpRoll = 55,
        Animation_JumpUncurl = 56,
        Animation_JumpFall = 57,
        Animation_JumpPad = 59,
        Animation_FlightFormationRelated_ = 60,
        Animation_Hang = 61,
        Animation_Trick = 62,
        Animation_Glide = 63,
        Animation_FlightFormationStill = 64,
        Animation_FlightFormationMove = 65,
        Animation_FlightFormationRelated = 66,
        Animation_FlightFormationRelated2 = 67,
        Animation_RollRelated = 68,
        Animation_JumpDash = 69,
        Animation_OnRail = 70,
        Animation_GrindHold = 73,
        Animation_GrindStart = 76,
        Animation_GrindEnd = 77,
        Animation_BottomFlyFormationRail = 78,
        Animation_SuperTeamBlastIntro = 82,
        Animation_SuperTeamBlast = 83,
        Animation_SuperVictoryPose = 84,
        Animation_SuperVictoryPoseEnd = 85,
        Animation_RingThrow = 90,
        Animation_LightDash = 90,
        Animation_PowerAirAttack = 90,
        Animation_CheeseAttack = 90,
        Animation_WallStand = 91,
        Animation_PowerAttack = 91,
        Animation_FlyBobsled = 92,
        Animation_WallJump = 92,
        Animation_PowerAttack2 = 92,
        Animation_BackFlip = 93,
        Animation_PowerAttack3Start = 93,
        Animation_SideFlip = 94,
        Animation_PowerAttack3 = 94,
        Animation_BackFlip2 = 95,
        Animation_PowerAttack3End = 95,
        Animation_LeafTornado = 96,
        Animation_PowerPunch2 = 96,
        Animation_HammerSwingStart = 97,
        Animation_PowerPunch3 = 97,
        Animation_HammerSwing = 98,
        Animation_PowerExtraAttack = 98,
        Animation_HammerSwingEnd = 99,
        Animation_HammerTornado = 100,
        Animation_HammerTornadoEnd = 101,
        Animation_HammerFloat = 102,
        Animation_PowerBobsled = 102,
        Animation_ThrowStar = 103,
        Animation_SlideKick = 104,
    };


    public enum ENUM_PLAYER_TYPE
    {
        PLAYER_TYPE_SPEED = 0,
        PLAYER_TYPE_FLY = 1,
        PLAYER_TYPE_POWER = 2,
        NUM_PLAYER_TYPE = 3,
    };


}